"""
tools/assess.py — assess_answer MCP tool.

Evaluates the user's answer to the comprehension check question.
Has full context: the question, the original explanation, and the
answer signals generated by generate_comprehension_check.

Assessment philosophy:
  - Generous with partial credit. Different phrasings of the same idea = correct.
  - Specific about gaps. "You're close" is not useful; naming the gap is.
  - Never penalises for not understanding. Re-explanation is a teaching moment.
"""

from __future__ import annotations

import json
import logging

import openai

from config import get_settings
from models.schemas import AssessAnswerInput, AssessAnswerOutput
from prompts.templates import assess_answer_prompt

logger = logging.getLogger(__name__)
settings = get_settings()

_client = openai.AsyncOpenAI(
    api_key=settings.groq_api_key,
    base_url="https://api.groq.com/openai/v1",
)


async def assess_answer(
    check_question: str,
    user_answer: str,
    explanation: str,
    correct_signals: list[str],
    misconception_signals: list[str],
    topic: str,
) -> dict:
    """
    Assess whether the user genuinely understood the concept.

    Args:
        check_question:        The question that was asked.
        user_answer:           Exactly what the user typed.
        explanation:           The original explanation for full context.
        correct_signals:       Patterns indicating correct understanding.
        misconception_signals: Patterns indicating a specific misconception.
        topic:                 Python topic name.

    Returns:
        AssessAnswerOutput as a dict:
        {
          "understood":       true/false,
          "score":            0-100,
          "feedback":         Coaching-language feedback,
          "misconception":    Specific misconception name or null,
          "re_explain_angle": Suggested re-explanation angle or null
        }
    """
    validated = AssessAnswerInput(
        check_question=check_question,
        user_answer=user_answer,
        explanation=explanation,
        correct_signals=correct_signals,
        misconception_signals=misconception_signals,
        topic=topic,
    )

    logger.info(
        "assess_answer called",
        topic=validated.topic,
        answer_length=len(validated.user_answer),
        correct_signals_count=len(validated.correct_signals),
    )

    prompt = assess_answer_prompt(
        check_question=validated.check_question,
        user_answer=validated.user_answer,
        explanation=validated.explanation,
        correct_signals=validated.correct_signals,
        misconception_signals=validated.misconception_signals,
        topic=validated.topic,
    )

    response = await _client.chat.completions.create(
        model=settings.groq_model,
        max_tokens=512,
        messages=[{"role": "user", "content": prompt}],
    )

    raw_text = (response.choices[0].message.content or "").strip()

    try:
        raw_dict = json.loads(raw_text)
    except json.JSONDecodeError as e:
        logger.error(
            "assess_answer json parse failed",
            raw_preview=raw_text[:200],
            error=str(e),
        )
        return AssessAnswerOutput(
            understood=False,
            score=50,
            feedback="Let me try explaining that from a different angle to make sure it clicks.",
            misconception=None,
            re_explain_angle="simplest possible working example",
        ).model_dump()

    output = AssessAnswerOutput(**raw_dict)

    logger.info(
        "assess_answer succeeded",
        topic=validated.topic,
        understood=output.understood,
        score=output.score,
        misconception=output.misconception,
    )

    return output.model_dump()
