"""initial schema

Revision ID: 000000000000
Revises:
Create Date: 2024-01-01 00:00:00.000000 UTC

WHY A HAND-WRITTEN MIGRATION:
  The first migration creates all tables from scratch.
  We write it by hand (rather than autogenerate) so we can:
    - Add inline comments explaining design decisions
    - Ensure JSONB columns are created correctly (not as TEXT)
    - Verify the composite index names match our naming convention
    - Control the creation order to satisfy FK constraints

  After this baseline, all future migrations will be autogenerated
  with `alembic revision --autogenerate -m "description"`.

TABLES CREATED (in FK-safe order):
  1. users          — no FK dependencies
  2. conversations  — FK → users
  3. messages       — FK → conversations
  4. skill_scores   — FK → users
  5. achievements   — FK → users
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import JSONB, UUID

# revision identifiers, used by Alembic
revision: str = "000000000000"
down_revision: str | None = None
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ── users ────────────────────────────────────────────────────────────────
    op.create_table(
        "users",
        sa.Column("id", UUID(as_uuid=True), primary_key=True, nullable=False),
        sa.Column("email", sa.String(255), nullable=False),
        sa.Column("hashed_password", sa.String(255), nullable=False),
        sa.Column("display_name", sa.String(100), nullable=False, server_default="Learner"),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.create_index("ix_users_email", "users", ["email"], unique=True)
    # text_pattern_ops enables prefix-matching on email (e.g., LIKE 'alice%')
    op.create_index(
        "ix_users_email_lower",
        "users",
        ["email"],
        postgresql_ops={"email": "text_pattern_ops"},
    )

    # ── conversations ─────────────────────────────────────────────────────────
    op.create_table(
        "conversations",
        sa.Column("id", UUID(as_uuid=True), primary_key=True, nullable=False),
        sa.Column(
            "user_id",
            UUID(as_uuid=True),
            sa.ForeignKey("users.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("title", sa.String(200), nullable=True),
        sa.Column(
            "last_message_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.create_index("ix_conversations_user_id", "conversations", ["user_id"])
    op.create_index("ix_conversations_last_message_at", "conversations", ["last_message_at"])
    op.create_index(
        "ix_conversations_user_last_msg",
        "conversations",
        ["user_id", "last_message_at"],
    )

    # ── messages ──────────────────────────────────────────────────────────────
    op.create_table(
        "messages",
        sa.Column("id", UUID(as_uuid=True), primary_key=True, nullable=False),
        sa.Column(
            "conversation_id",
            UUID(as_uuid=True),
            sa.ForeignKey("conversations.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("role", sa.String(20), nullable=False),
        sa.Column("content", sa.Text, nullable=False),
        sa.Column("topic_detected", sa.String(100), nullable=True),
        sa.Column("tool_calls_json", JSONB, nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.create_index("ix_messages_conversation_id", "messages", ["conversation_id"])
    op.create_index("ix_messages_topic", "messages", ["topic_detected"])
    op.create_index(
        "ix_messages_conversation_created",
        "messages",
        ["conversation_id", "created_at"],
    )

    # ── skill_scores ──────────────────────────────────────────────────────────
    op.create_table(
        "skill_scores",
        sa.Column("id", UUID(as_uuid=True), primary_key=True, nullable=False),
        sa.Column(
            "user_id",
            UUID(as_uuid=True),
            sa.ForeignKey("users.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("topic", sa.String(100), nullable=False),
        sa.Column("score", sa.Float, nullable=False, server_default="0.0"),
        sa.Column("level", sa.String(20), nullable=False, server_default="beginner"),
        sa.Column("attempts", sa.Integer, nullable=False, server_default="0"),
        sa.Column("correct_streak", sa.Integer, nullable=False, server_default="0"),
        sa.Column("longest_streak", sa.Integer, nullable=False, server_default="0"),
        sa.Column("last_assessed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        # One row per (user, topic) — enforced at DB level
        sa.UniqueConstraint("user_id", "topic", name="uq_skill_scores_user_topic"),
    )
    op.create_index("ix_skill_scores_user_id", "skill_scores", ["user_id"])
    op.create_index(
        "ix_skill_scores_user_score",
        "skill_scores",
        ["user_id", "score"],
    )

    # ── achievements ──────────────────────────────────────────────────────────
    op.create_table(
        "achievements",
        sa.Column("id", UUID(as_uuid=True), primary_key=True, nullable=False),
        sa.Column(
            "user_id",
            UUID(as_uuid=True),
            sa.ForeignKey("users.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("achievement_type", sa.String(50), nullable=False),
        sa.Column("topic", sa.String(100), nullable=True),
        sa.Column(
            "earned_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("metadata_json", JSONB, nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        # Prevents duplicate topic-specific badges.
        # Does NOT protect NULL topic rows (NULL != NULL in SQL UNIQUE).
        # AchievementRepository.award() has an explicit exists() check for that.
        sa.UniqueConstraint(
            "user_id", "achievement_type", "topic",
            name="uq_achievements_user_type_topic",
        ),
    )
    op.create_index("ix_achievements_user_id", "achievements", ["user_id"])
    op.create_index(
        "ix_achievements_user_earned",
        "achievements",
        ["user_id", "earned_at"],
    )


def downgrade() -> None:
    # Drop in reverse FK dependency order
    op.drop_table("achievements")
    op.drop_table("skill_scores")
    op.drop_table("messages")
    op.drop_table("conversations")
    op.drop_table("users")
